developmnet: &default
  admin_name: Frist User
  admin_email: user@ex.com
  admin_password: changeme
  domain_name: ex.com
  secret_key_base: fc44444444444444444
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
  host_name: "6e0fd751.ngrok.com"
  authy_key: <%= ENV["AUTHY_KEY"] %>
  rollbar: '7f4b0000000000000'

test:
  <<: *default
  secret_key_base: 9843434333333333333333

production:
        <<: *default
        admin_name: <%= ENV["ADMIN_NAME"] %>
        admin_email: <%= ENV["ADMIN_EMAIL"] %>
        admin_password: <%= ENV["ADMIN_PASSWORD"] %>
        domain_name: <%= ENV["DOMAIN_NAME"] %>
        secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
